/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthOnboardingRouteImport } from './routes/auth/onboarding'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthEmailVerificationRouteImport } from './routes/auth/email-verification'
import { Route as DashboardSlugRouteImport } from './routes/_dashboard/$slug'
import { Route as DashboardSlugReportsRouteImport } from './routes/_dashboard/$slug/reports'
import { Route as DashboardSlugProfileRouteImport } from './routes/_dashboard/$slug/profile'
import { Route as DashboardSlugHomeRouteImport } from './routes/_dashboard/$slug/home'
import { Route as DashboardSlugTransactionsIndexRouteImport } from './routes/_dashboard/$slug/transactions.index'
import { Route as DashboardSlugTagsIndexRouteImport } from './routes/_dashboard/$slug/tags/index'
import { Route as DashboardSlugOrganizationIndexRouteImport } from './routes/_dashboard/$slug/organization/index'
import { Route as DashboardSlugCostCentersIndexRouteImport } from './routes/_dashboard/$slug/cost-centers/index'
import { Route as DashboardSlugCategoriesIndexRouteImport } from './routes/_dashboard/$slug/categories/index'
import { Route as DashboardSlugBillsIndexRouteImport } from './routes/_dashboard/$slug/bills/index'
import { Route as DashboardSlugBankAccountsIndexRouteImport } from './routes/_dashboard/$slug/bank-accounts.index'
import { Route as DashboardSlugTransactionsTransactionIdRouteImport } from './routes/_dashboard/$slug/transactions.$transactionId'
import { Route as DashboardSlugTagsTagIdRouteImport } from './routes/_dashboard/$slug/tags/$tagId'
import { Route as DashboardSlugOrganizationTeamsRouteImport } from './routes/_dashboard/$slug/organization/teams'
import { Route as DashboardSlugOrganizationMembersRouteImport } from './routes/_dashboard/$slug/organization/members'
import { Route as DashboardSlugOrganizationInvitesRouteImport } from './routes/_dashboard/$slug/organization/invites'
import { Route as DashboardSlugCostCentersCostCenterIdRouteImport } from './routes/_dashboard/$slug/cost-centers/$costCenterId'
import { Route as DashboardSlugCategoriesCategoryIdRouteImport } from './routes/_dashboard/$slug/categories/$categoryId'
import { Route as DashboardSlugBankAccountsBankAccountIdRouteImport } from './routes/_dashboard/$slug/bank-accounts.$bankAccountId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEmailVerificationRoute = AuthEmailVerificationRouteImport.update({
  id: '/email-verification',
  path: '/email-verification',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardSlugRoute = DashboardSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSlugReportsRoute = DashboardSlugReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardSlugRoute,
} as any)
const DashboardSlugProfileRoute = DashboardSlugProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardSlugRoute,
} as any)
const DashboardSlugHomeRoute = DashboardSlugHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => DashboardSlugRoute,
} as any)
const DashboardSlugTransactionsIndexRoute =
  DashboardSlugTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => DashboardSlugRoute,
  } as any)
const DashboardSlugTagsIndexRoute = DashboardSlugTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => DashboardSlugRoute,
} as any)
const DashboardSlugOrganizationIndexRoute =
  DashboardSlugOrganizationIndexRouteImport.update({
    id: '/organization/',
    path: '/organization/',
    getParentRoute: () => DashboardSlugRoute,
  } as any)
const DashboardSlugCostCentersIndexRoute =
  DashboardSlugCostCentersIndexRouteImport.update({
    id: '/cost-centers/',
    path: '/cost-centers/',
    getParentRoute: () => DashboardSlugRoute,
  } as any)
const DashboardSlugCategoriesIndexRoute =
  DashboardSlugCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => DashboardSlugRoute,
  } as any)
const DashboardSlugBillsIndexRoute = DashboardSlugBillsIndexRouteImport.update({
  id: '/bills/',
  path: '/bills/',
  getParentRoute: () => DashboardSlugRoute,
} as any)
const DashboardSlugBankAccountsIndexRoute =
  DashboardSlugBankAccountsIndexRouteImport.update({
    id: '/bank-accounts/',
    path: '/bank-accounts/',
    getParentRoute: () => DashboardSlugRoute,
  } as any)
const DashboardSlugTransactionsTransactionIdRoute =
  DashboardSlugTransactionsTransactionIdRouteImport.update({
    id: '/transactions/$transactionId',
    path: '/transactions/$transactionId',
    getParentRoute: () => DashboardSlugRoute,
  } as any)
const DashboardSlugTagsTagIdRoute = DashboardSlugTagsTagIdRouteImport.update({
  id: '/tags/$tagId',
  path: '/tags/$tagId',
  getParentRoute: () => DashboardSlugRoute,
} as any)
const DashboardSlugOrganizationTeamsRoute =
  DashboardSlugOrganizationTeamsRouteImport.update({
    id: '/organization/teams',
    path: '/organization/teams',
    getParentRoute: () => DashboardSlugRoute,
  } as any)
const DashboardSlugOrganizationMembersRoute =
  DashboardSlugOrganizationMembersRouteImport.update({
    id: '/organization/members',
    path: '/organization/members',
    getParentRoute: () => DashboardSlugRoute,
  } as any)
const DashboardSlugOrganizationInvitesRoute =
  DashboardSlugOrganizationInvitesRouteImport.update({
    id: '/organization/invites',
    path: '/organization/invites',
    getParentRoute: () => DashboardSlugRoute,
  } as any)
const DashboardSlugCostCentersCostCenterIdRoute =
  DashboardSlugCostCentersCostCenterIdRouteImport.update({
    id: '/cost-centers/$costCenterId',
    path: '/cost-centers/$costCenterId',
    getParentRoute: () => DashboardSlugRoute,
  } as any)
const DashboardSlugCategoriesCategoryIdRoute =
  DashboardSlugCategoriesCategoryIdRouteImport.update({
    id: '/categories/$categoryId',
    path: '/categories/$categoryId',
    getParentRoute: () => DashboardSlugRoute,
  } as any)
const DashboardSlugBankAccountsBankAccountIdRoute =
  DashboardSlugBankAccountsBankAccountIdRouteImport.update({
    id: '/bank-accounts/$bankAccountId',
    path: '/bank-accounts/$bankAccountId',
    getParentRoute: () => DashboardSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteWithChildren
  '/$slug': typeof DashboardSlugRouteWithChildren
  '/auth/email-verification': typeof AuthEmailVerificationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/$slug/home': typeof DashboardSlugHomeRoute
  '/$slug/profile': typeof DashboardSlugProfileRoute
  '/$slug/reports': typeof DashboardSlugReportsRoute
  '/$slug/bank-accounts/$bankAccountId': typeof DashboardSlugBankAccountsBankAccountIdRoute
  '/$slug/categories/$categoryId': typeof DashboardSlugCategoriesCategoryIdRoute
  '/$slug/cost-centers/$costCenterId': typeof DashboardSlugCostCentersCostCenterIdRoute
  '/$slug/organization/invites': typeof DashboardSlugOrganizationInvitesRoute
  '/$slug/organization/members': typeof DashboardSlugOrganizationMembersRoute
  '/$slug/organization/teams': typeof DashboardSlugOrganizationTeamsRoute
  '/$slug/tags/$tagId': typeof DashboardSlugTagsTagIdRoute
  '/$slug/transactions/$transactionId': typeof DashboardSlugTransactionsTransactionIdRoute
  '/$slug/bank-accounts': typeof DashboardSlugBankAccountsIndexRoute
  '/$slug/bills': typeof DashboardSlugBillsIndexRoute
  '/$slug/categories': typeof DashboardSlugCategoriesIndexRoute
  '/$slug/cost-centers': typeof DashboardSlugCostCentersIndexRoute
  '/$slug/organization': typeof DashboardSlugOrganizationIndexRoute
  '/$slug/tags': typeof DashboardSlugTagsIndexRoute
  '/$slug/transactions': typeof DashboardSlugTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/$slug': typeof DashboardSlugRouteWithChildren
  '/auth/email-verification': typeof AuthEmailVerificationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/$slug/home': typeof DashboardSlugHomeRoute
  '/$slug/profile': typeof DashboardSlugProfileRoute
  '/$slug/reports': typeof DashboardSlugReportsRoute
  '/$slug/bank-accounts/$bankAccountId': typeof DashboardSlugBankAccountsBankAccountIdRoute
  '/$slug/categories/$categoryId': typeof DashboardSlugCategoriesCategoryIdRoute
  '/$slug/cost-centers/$costCenterId': typeof DashboardSlugCostCentersCostCenterIdRoute
  '/$slug/organization/invites': typeof DashboardSlugOrganizationInvitesRoute
  '/$slug/organization/members': typeof DashboardSlugOrganizationMembersRoute
  '/$slug/organization/teams': typeof DashboardSlugOrganizationTeamsRoute
  '/$slug/tags/$tagId': typeof DashboardSlugTagsTagIdRoute
  '/$slug/transactions/$transactionId': typeof DashboardSlugTransactionsTransactionIdRoute
  '/$slug/bank-accounts': typeof DashboardSlugBankAccountsIndexRoute
  '/$slug/bills': typeof DashboardSlugBillsIndexRoute
  '/$slug/categories': typeof DashboardSlugCategoriesIndexRoute
  '/$slug/cost-centers': typeof DashboardSlugCostCentersIndexRoute
  '/$slug/organization': typeof DashboardSlugOrganizationIndexRoute
  '/$slug/tags': typeof DashboardSlugTagsIndexRoute
  '/$slug/transactions': typeof DashboardSlugTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_dashboard/$slug': typeof DashboardSlugRouteWithChildren
  '/auth/email-verification': typeof AuthEmailVerificationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/_dashboard/$slug/home': typeof DashboardSlugHomeRoute
  '/_dashboard/$slug/profile': typeof DashboardSlugProfileRoute
  '/_dashboard/$slug/reports': typeof DashboardSlugReportsRoute
  '/_dashboard/$slug/bank-accounts/$bankAccountId': typeof DashboardSlugBankAccountsBankAccountIdRoute
  '/_dashboard/$slug/categories/$categoryId': typeof DashboardSlugCategoriesCategoryIdRoute
  '/_dashboard/$slug/cost-centers/$costCenterId': typeof DashboardSlugCostCentersCostCenterIdRoute
  '/_dashboard/$slug/organization/invites': typeof DashboardSlugOrganizationInvitesRoute
  '/_dashboard/$slug/organization/members': typeof DashboardSlugOrganizationMembersRoute
  '/_dashboard/$slug/organization/teams': typeof DashboardSlugOrganizationTeamsRoute
  '/_dashboard/$slug/tags/$tagId': typeof DashboardSlugTagsTagIdRoute
  '/_dashboard/$slug/transactions/$transactionId': typeof DashboardSlugTransactionsTransactionIdRoute
  '/_dashboard/$slug/bank-accounts/': typeof DashboardSlugBankAccountsIndexRoute
  '/_dashboard/$slug/bills/': typeof DashboardSlugBillsIndexRoute
  '/_dashboard/$slug/categories/': typeof DashboardSlugCategoriesIndexRoute
  '/_dashboard/$slug/cost-centers/': typeof DashboardSlugCostCentersIndexRoute
  '/_dashboard/$slug/organization/': typeof DashboardSlugOrganizationIndexRoute
  '/_dashboard/$slug/tags/': typeof DashboardSlugTagsIndexRoute
  '/_dashboard/$slug/transactions/': typeof DashboardSlugTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/$slug'
    | '/auth/email-verification'
    | '/auth/forgot-password'
    | '/auth/onboarding'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/$slug/home'
    | '/$slug/profile'
    | '/$slug/reports'
    | '/$slug/bank-accounts/$bankAccountId'
    | '/$slug/categories/$categoryId'
    | '/$slug/cost-centers/$costCenterId'
    | '/$slug/organization/invites'
    | '/$slug/organization/members'
    | '/$slug/organization/teams'
    | '/$slug/tags/$tagId'
    | '/$slug/transactions/$transactionId'
    | '/$slug/bank-accounts'
    | '/$slug/bills'
    | '/$slug/categories'
    | '/$slug/cost-centers'
    | '/$slug/organization'
    | '/$slug/tags'
    | '/$slug/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/$slug'
    | '/auth/email-verification'
    | '/auth/forgot-password'
    | '/auth/onboarding'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/$slug/home'
    | '/$slug/profile'
    | '/$slug/reports'
    | '/$slug/bank-accounts/$bankAccountId'
    | '/$slug/categories/$categoryId'
    | '/$slug/cost-centers/$costCenterId'
    | '/$slug/organization/invites'
    | '/$slug/organization/members'
    | '/$slug/organization/teams'
    | '/$slug/tags/$tagId'
    | '/$slug/transactions/$transactionId'
    | '/$slug/bank-accounts'
    | '/$slug/bills'
    | '/$slug/categories'
    | '/$slug/cost-centers'
    | '/$slug/organization'
    | '/$slug/tags'
    | '/$slug/transactions'
  id:
    | '__root__'
    | '/_dashboard'
    | '/auth'
    | '/_dashboard/$slug'
    | '/auth/email-verification'
    | '/auth/forgot-password'
    | '/auth/onboarding'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/_dashboard/$slug/home'
    | '/_dashboard/$slug/profile'
    | '/_dashboard/$slug/reports'
    | '/_dashboard/$slug/bank-accounts/$bankAccountId'
    | '/_dashboard/$slug/categories/$categoryId'
    | '/_dashboard/$slug/cost-centers/$costCenterId'
    | '/_dashboard/$slug/organization/invites'
    | '/_dashboard/$slug/organization/members'
    | '/_dashboard/$slug/organization/teams'
    | '/_dashboard/$slug/tags/$tagId'
    | '/_dashboard/$slug/transactions/$transactionId'
    | '/_dashboard/$slug/bank-accounts/'
    | '/_dashboard/$slug/bills/'
    | '/_dashboard/$slug/categories/'
    | '/_dashboard/$slug/cost-centers/'
    | '/_dashboard/$slug/organization/'
    | '/_dashboard/$slug/tags/'
    | '/_dashboard/$slug/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/onboarding': {
      id: '/auth/onboarding'
      path: '/onboarding'
      fullPath: '/auth/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/email-verification': {
      id: '/auth/email-verification'
      path: '/email-verification'
      fullPath: '/auth/email-verification'
      preLoaderRoute: typeof AuthEmailVerificationRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_dashboard/$slug': {
      id: '/_dashboard/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof DashboardSlugRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/$slug/reports': {
      id: '/_dashboard/$slug/reports'
      path: '/reports'
      fullPath: '/$slug/reports'
      preLoaderRoute: typeof DashboardSlugReportsRouteImport
      parentRoute: typeof DashboardSlugRoute
    }
    '/_dashboard/$slug/profile': {
      id: '/_dashboard/$slug/profile'
      path: '/profile'
      fullPath: '/$slug/profile'
      preLoaderRoute: typeof DashboardSlugProfileRouteImport
      parentRoute: typeof DashboardSlugRoute
    }
    '/_dashboard/$slug/home': {
      id: '/_dashboard/$slug/home'
      path: '/home'
      fullPath: '/$slug/home'
      preLoaderRoute: typeof DashboardSlugHomeRouteImport
      parentRoute: typeof DashboardSlugRoute
    }
    '/_dashboard/$slug/transactions/': {
      id: '/_dashboard/$slug/transactions/'
      path: '/transactions'
      fullPath: '/$slug/transactions'
      preLoaderRoute: typeof DashboardSlugTransactionsIndexRouteImport
      parentRoute: typeof DashboardSlugRoute
    }
    '/_dashboard/$slug/tags/': {
      id: '/_dashboard/$slug/tags/'
      path: '/tags'
      fullPath: '/$slug/tags'
      preLoaderRoute: typeof DashboardSlugTagsIndexRouteImport
      parentRoute: typeof DashboardSlugRoute
    }
    '/_dashboard/$slug/organization/': {
      id: '/_dashboard/$slug/organization/'
      path: '/organization'
      fullPath: '/$slug/organization'
      preLoaderRoute: typeof DashboardSlugOrganizationIndexRouteImport
      parentRoute: typeof DashboardSlugRoute
    }
    '/_dashboard/$slug/cost-centers/': {
      id: '/_dashboard/$slug/cost-centers/'
      path: '/cost-centers'
      fullPath: '/$slug/cost-centers'
      preLoaderRoute: typeof DashboardSlugCostCentersIndexRouteImport
      parentRoute: typeof DashboardSlugRoute
    }
    '/_dashboard/$slug/categories/': {
      id: '/_dashboard/$slug/categories/'
      path: '/categories'
      fullPath: '/$slug/categories'
      preLoaderRoute: typeof DashboardSlugCategoriesIndexRouteImport
      parentRoute: typeof DashboardSlugRoute
    }
    '/_dashboard/$slug/bills/': {
      id: '/_dashboard/$slug/bills/'
      path: '/bills'
      fullPath: '/$slug/bills'
      preLoaderRoute: typeof DashboardSlugBillsIndexRouteImport
      parentRoute: typeof DashboardSlugRoute
    }
    '/_dashboard/$slug/bank-accounts/': {
      id: '/_dashboard/$slug/bank-accounts/'
      path: '/bank-accounts'
      fullPath: '/$slug/bank-accounts'
      preLoaderRoute: typeof DashboardSlugBankAccountsIndexRouteImport
      parentRoute: typeof DashboardSlugRoute
    }
    '/_dashboard/$slug/transactions/$transactionId': {
      id: '/_dashboard/$slug/transactions/$transactionId'
      path: '/transactions/$transactionId'
      fullPath: '/$slug/transactions/$transactionId'
      preLoaderRoute: typeof DashboardSlugTransactionsTransactionIdRouteImport
      parentRoute: typeof DashboardSlugRoute
    }
    '/_dashboard/$slug/tags/$tagId': {
      id: '/_dashboard/$slug/tags/$tagId'
      path: '/tags/$tagId'
      fullPath: '/$slug/tags/$tagId'
      preLoaderRoute: typeof DashboardSlugTagsTagIdRouteImport
      parentRoute: typeof DashboardSlugRoute
    }
    '/_dashboard/$slug/organization/teams': {
      id: '/_dashboard/$slug/organization/teams'
      path: '/organization/teams'
      fullPath: '/$slug/organization/teams'
      preLoaderRoute: typeof DashboardSlugOrganizationTeamsRouteImport
      parentRoute: typeof DashboardSlugRoute
    }
    '/_dashboard/$slug/organization/members': {
      id: '/_dashboard/$slug/organization/members'
      path: '/organization/members'
      fullPath: '/$slug/organization/members'
      preLoaderRoute: typeof DashboardSlugOrganizationMembersRouteImport
      parentRoute: typeof DashboardSlugRoute
    }
    '/_dashboard/$slug/organization/invites': {
      id: '/_dashboard/$slug/organization/invites'
      path: '/organization/invites'
      fullPath: '/$slug/organization/invites'
      preLoaderRoute: typeof DashboardSlugOrganizationInvitesRouteImport
      parentRoute: typeof DashboardSlugRoute
    }
    '/_dashboard/$slug/cost-centers/$costCenterId': {
      id: '/_dashboard/$slug/cost-centers/$costCenterId'
      path: '/cost-centers/$costCenterId'
      fullPath: '/$slug/cost-centers/$costCenterId'
      preLoaderRoute: typeof DashboardSlugCostCentersCostCenterIdRouteImport
      parentRoute: typeof DashboardSlugRoute
    }
    '/_dashboard/$slug/categories/$categoryId': {
      id: '/_dashboard/$slug/categories/$categoryId'
      path: '/categories/$categoryId'
      fullPath: '/$slug/categories/$categoryId'
      preLoaderRoute: typeof DashboardSlugCategoriesCategoryIdRouteImport
      parentRoute: typeof DashboardSlugRoute
    }
    '/_dashboard/$slug/bank-accounts/$bankAccountId': {
      id: '/_dashboard/$slug/bank-accounts/$bankAccountId'
      path: '/bank-accounts/$bankAccountId'
      fullPath: '/$slug/bank-accounts/$bankAccountId'
      preLoaderRoute: typeof DashboardSlugBankAccountsBankAccountIdRouteImport
      parentRoute: typeof DashboardSlugRoute
    }
  }
}

interface DashboardSlugRouteChildren {
  DashboardSlugHomeRoute: typeof DashboardSlugHomeRoute
  DashboardSlugProfileRoute: typeof DashboardSlugProfileRoute
  DashboardSlugReportsRoute: typeof DashboardSlugReportsRoute
  DashboardSlugBankAccountsBankAccountIdRoute: typeof DashboardSlugBankAccountsBankAccountIdRoute
  DashboardSlugCategoriesCategoryIdRoute: typeof DashboardSlugCategoriesCategoryIdRoute
  DashboardSlugCostCentersCostCenterIdRoute: typeof DashboardSlugCostCentersCostCenterIdRoute
  DashboardSlugOrganizationInvitesRoute: typeof DashboardSlugOrganizationInvitesRoute
  DashboardSlugOrganizationMembersRoute: typeof DashboardSlugOrganizationMembersRoute
  DashboardSlugOrganizationTeamsRoute: typeof DashboardSlugOrganizationTeamsRoute
  DashboardSlugTagsTagIdRoute: typeof DashboardSlugTagsTagIdRoute
  DashboardSlugTransactionsTransactionIdRoute: typeof DashboardSlugTransactionsTransactionIdRoute
  DashboardSlugBankAccountsIndexRoute: typeof DashboardSlugBankAccountsIndexRoute
  DashboardSlugBillsIndexRoute: typeof DashboardSlugBillsIndexRoute
  DashboardSlugCategoriesIndexRoute: typeof DashboardSlugCategoriesIndexRoute
  DashboardSlugCostCentersIndexRoute: typeof DashboardSlugCostCentersIndexRoute
  DashboardSlugOrganizationIndexRoute: typeof DashboardSlugOrganizationIndexRoute
  DashboardSlugTagsIndexRoute: typeof DashboardSlugTagsIndexRoute
  DashboardSlugTransactionsIndexRoute: typeof DashboardSlugTransactionsIndexRoute
}

const DashboardSlugRouteChildren: DashboardSlugRouteChildren = {
  DashboardSlugHomeRoute: DashboardSlugHomeRoute,
  DashboardSlugProfileRoute: DashboardSlugProfileRoute,
  DashboardSlugReportsRoute: DashboardSlugReportsRoute,
  DashboardSlugBankAccountsBankAccountIdRoute:
    DashboardSlugBankAccountsBankAccountIdRoute,
  DashboardSlugCategoriesCategoryIdRoute:
    DashboardSlugCategoriesCategoryIdRoute,
  DashboardSlugCostCentersCostCenterIdRoute:
    DashboardSlugCostCentersCostCenterIdRoute,
  DashboardSlugOrganizationInvitesRoute: DashboardSlugOrganizationInvitesRoute,
  DashboardSlugOrganizationMembersRoute: DashboardSlugOrganizationMembersRoute,
  DashboardSlugOrganizationTeamsRoute: DashboardSlugOrganizationTeamsRoute,
  DashboardSlugTagsTagIdRoute: DashboardSlugTagsTagIdRoute,
  DashboardSlugTransactionsTransactionIdRoute:
    DashboardSlugTransactionsTransactionIdRoute,
  DashboardSlugBankAccountsIndexRoute: DashboardSlugBankAccountsIndexRoute,
  DashboardSlugBillsIndexRoute: DashboardSlugBillsIndexRoute,
  DashboardSlugCategoriesIndexRoute: DashboardSlugCategoriesIndexRoute,
  DashboardSlugCostCentersIndexRoute: DashboardSlugCostCentersIndexRoute,
  DashboardSlugOrganizationIndexRoute: DashboardSlugOrganizationIndexRoute,
  DashboardSlugTagsIndexRoute: DashboardSlugTagsIndexRoute,
  DashboardSlugTransactionsIndexRoute: DashboardSlugTransactionsIndexRoute,
}

const DashboardSlugRouteWithChildren = DashboardSlugRoute._addFileChildren(
  DashboardSlugRouteChildren,
)

interface DashboardRouteChildren {
  DashboardSlugRoute: typeof DashboardSlugRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardSlugRoute: DashboardSlugRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface AuthRouteChildren {
  AuthEmailVerificationRoute: typeof AuthEmailVerificationRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthOnboardingRoute: typeof AuthOnboardingRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthEmailVerificationRoute: AuthEmailVerificationRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthOnboardingRoute: AuthOnboardingRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
