/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthEmailVerificationRouteImport } from './routes/auth/email-verification'
import { Route as SlugOnboardingRouteImport } from './routes/$slug/onboarding'
import { Route as SlugDashboardRouteImport } from './routes/$slug/_dashboard'
import { Route as SlugDashboardReportsRouteImport } from './routes/$slug/_dashboard/reports'
import { Route as SlugDashboardProfileRouteImport } from './routes/$slug/_dashboard/profile'
import { Route as SlugDashboardHomeRouteImport } from './routes/$slug/_dashboard/home'
import { Route as SlugDashboardTransactionsIndexRouteImport } from './routes/$slug/_dashboard/transactions.index'
import { Route as SlugDashboardTagsIndexRouteImport } from './routes/$slug/_dashboard/tags/index'
import { Route as SlugDashboardOrganizationIndexRouteImport } from './routes/$slug/_dashboard/organization/index'
import { Route as SlugDashboardCostCentersIndexRouteImport } from './routes/$slug/_dashboard/cost-centers/index'
import { Route as SlugDashboardCategoriesIndexRouteImport } from './routes/$slug/_dashboard/categories/index'
import { Route as SlugDashboardBudgetsIndexRouteImport } from './routes/$slug/_dashboard/budgets/index'
import { Route as SlugDashboardBillsIndexRouteImport } from './routes/$slug/_dashboard/bills/index'
import { Route as SlugDashboardBankAccountsIndexRouteImport } from './routes/$slug/_dashboard/bank-accounts.index'
import { Route as SlugDashboardTransactionsTransactionIdRouteImport } from './routes/$slug/_dashboard/transactions.$transactionId'
import { Route as SlugDashboardTagsTagIdRouteImport } from './routes/$slug/_dashboard/tags/$tagId'
import { Route as SlugDashboardOrganizationTeamsRouteImport } from './routes/$slug/_dashboard/organization/teams'
import { Route as SlugDashboardOrganizationMembersRouteImport } from './routes/$slug/_dashboard/organization/members'
import { Route as SlugDashboardOrganizationInvitesRouteImport } from './routes/$slug/_dashboard/organization/invites'
import { Route as SlugDashboardCostCentersCostCenterIdRouteImport } from './routes/$slug/_dashboard/cost-centers/$costCenterId'
import { Route as SlugDashboardCategoriesCategoryIdRouteImport } from './routes/$slug/_dashboard/categories/$categoryId'
import { Route as SlugDashboardBudgetsBudgetIdRouteImport } from './routes/$slug/_dashboard/budgets/$budgetId'
import { Route as SlugDashboardBankAccountsBankAccountIdRouteImport } from './routes/$slug/_dashboard/bank-accounts.$bankAccountId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEmailVerificationRoute = AuthEmailVerificationRouteImport.update({
  id: '/email-verification',
  path: '/email-verification',
  getParentRoute: () => AuthRoute,
} as any)
const SlugOnboardingRoute = SlugOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => SlugRoute,
} as any)
const SlugDashboardRoute = SlugDashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => SlugRoute,
} as any)
const SlugDashboardReportsRoute = SlugDashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => SlugDashboardRoute,
} as any)
const SlugDashboardProfileRoute = SlugDashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SlugDashboardRoute,
} as any)
const SlugDashboardHomeRoute = SlugDashboardHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => SlugDashboardRoute,
} as any)
const SlugDashboardTransactionsIndexRoute =
  SlugDashboardTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => SlugDashboardRoute,
  } as any)
const SlugDashboardTagsIndexRoute = SlugDashboardTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => SlugDashboardRoute,
} as any)
const SlugDashboardOrganizationIndexRoute =
  SlugDashboardOrganizationIndexRouteImport.update({
    id: '/organization/',
    path: '/organization/',
    getParentRoute: () => SlugDashboardRoute,
  } as any)
const SlugDashboardCostCentersIndexRoute =
  SlugDashboardCostCentersIndexRouteImport.update({
    id: '/cost-centers/',
    path: '/cost-centers/',
    getParentRoute: () => SlugDashboardRoute,
  } as any)
const SlugDashboardCategoriesIndexRoute =
  SlugDashboardCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => SlugDashboardRoute,
  } as any)
const SlugDashboardBudgetsIndexRoute =
  SlugDashboardBudgetsIndexRouteImport.update({
    id: '/budgets/',
    path: '/budgets/',
    getParentRoute: () => SlugDashboardRoute,
  } as any)
const SlugDashboardBillsIndexRoute = SlugDashboardBillsIndexRouteImport.update({
  id: '/bills/',
  path: '/bills/',
  getParentRoute: () => SlugDashboardRoute,
} as any)
const SlugDashboardBankAccountsIndexRoute =
  SlugDashboardBankAccountsIndexRouteImport.update({
    id: '/bank-accounts/',
    path: '/bank-accounts/',
    getParentRoute: () => SlugDashboardRoute,
  } as any)
const SlugDashboardTransactionsTransactionIdRoute =
  SlugDashboardTransactionsTransactionIdRouteImport.update({
    id: '/transactions/$transactionId',
    path: '/transactions/$transactionId',
    getParentRoute: () => SlugDashboardRoute,
  } as any)
const SlugDashboardTagsTagIdRoute = SlugDashboardTagsTagIdRouteImport.update({
  id: '/tags/$tagId',
  path: '/tags/$tagId',
  getParentRoute: () => SlugDashboardRoute,
} as any)
const SlugDashboardOrganizationTeamsRoute =
  SlugDashboardOrganizationTeamsRouteImport.update({
    id: '/organization/teams',
    path: '/organization/teams',
    getParentRoute: () => SlugDashboardRoute,
  } as any)
const SlugDashboardOrganizationMembersRoute =
  SlugDashboardOrganizationMembersRouteImport.update({
    id: '/organization/members',
    path: '/organization/members',
    getParentRoute: () => SlugDashboardRoute,
  } as any)
const SlugDashboardOrganizationInvitesRoute =
  SlugDashboardOrganizationInvitesRouteImport.update({
    id: '/organization/invites',
    path: '/organization/invites',
    getParentRoute: () => SlugDashboardRoute,
  } as any)
const SlugDashboardCostCentersCostCenterIdRoute =
  SlugDashboardCostCentersCostCenterIdRouteImport.update({
    id: '/cost-centers/$costCenterId',
    path: '/cost-centers/$costCenterId',
    getParentRoute: () => SlugDashboardRoute,
  } as any)
const SlugDashboardCategoriesCategoryIdRoute =
  SlugDashboardCategoriesCategoryIdRouteImport.update({
    id: '/categories/$categoryId',
    path: '/categories/$categoryId',
    getParentRoute: () => SlugDashboardRoute,
  } as any)
const SlugDashboardBudgetsBudgetIdRoute =
  SlugDashboardBudgetsBudgetIdRouteImport.update({
    id: '/budgets/$budgetId',
    path: '/budgets/$budgetId',
    getParentRoute: () => SlugDashboardRoute,
  } as any)
const SlugDashboardBankAccountsBankAccountIdRoute =
  SlugDashboardBankAccountsBankAccountIdRouteImport.update({
    id: '/bank-accounts/$bankAccountId',
    path: '/bank-accounts/$bankAccountId',
    getParentRoute: () => SlugDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$slug': typeof SlugDashboardRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/$slug/onboarding': typeof SlugOnboardingRoute
  '/auth/email-verification': typeof AuthEmailVerificationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/$slug/home': typeof SlugDashboardHomeRoute
  '/$slug/profile': typeof SlugDashboardProfileRoute
  '/$slug/reports': typeof SlugDashboardReportsRoute
  '/$slug/bank-accounts/$bankAccountId': typeof SlugDashboardBankAccountsBankAccountIdRoute
  '/$slug/budgets/$budgetId': typeof SlugDashboardBudgetsBudgetIdRoute
  '/$slug/categories/$categoryId': typeof SlugDashboardCategoriesCategoryIdRoute
  '/$slug/cost-centers/$costCenterId': typeof SlugDashboardCostCentersCostCenterIdRoute
  '/$slug/organization/invites': typeof SlugDashboardOrganizationInvitesRoute
  '/$slug/organization/members': typeof SlugDashboardOrganizationMembersRoute
  '/$slug/organization/teams': typeof SlugDashboardOrganizationTeamsRoute
  '/$slug/tags/$tagId': typeof SlugDashboardTagsTagIdRoute
  '/$slug/transactions/$transactionId': typeof SlugDashboardTransactionsTransactionIdRoute
  '/$slug/bank-accounts': typeof SlugDashboardBankAccountsIndexRoute
  '/$slug/bills': typeof SlugDashboardBillsIndexRoute
  '/$slug/budgets': typeof SlugDashboardBudgetsIndexRoute
  '/$slug/categories': typeof SlugDashboardCategoriesIndexRoute
  '/$slug/cost-centers': typeof SlugDashboardCostCentersIndexRoute
  '/$slug/organization': typeof SlugDashboardOrganizationIndexRoute
  '/$slug/tags': typeof SlugDashboardTagsIndexRoute
  '/$slug/transactions': typeof SlugDashboardTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/$slug': typeof SlugDashboardRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/$slug/onboarding': typeof SlugOnboardingRoute
  '/auth/email-verification': typeof AuthEmailVerificationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/$slug/home': typeof SlugDashboardHomeRoute
  '/$slug/profile': typeof SlugDashboardProfileRoute
  '/$slug/reports': typeof SlugDashboardReportsRoute
  '/$slug/bank-accounts/$bankAccountId': typeof SlugDashboardBankAccountsBankAccountIdRoute
  '/$slug/budgets/$budgetId': typeof SlugDashboardBudgetsBudgetIdRoute
  '/$slug/categories/$categoryId': typeof SlugDashboardCategoriesCategoryIdRoute
  '/$slug/cost-centers/$costCenterId': typeof SlugDashboardCostCentersCostCenterIdRoute
  '/$slug/organization/invites': typeof SlugDashboardOrganizationInvitesRoute
  '/$slug/organization/members': typeof SlugDashboardOrganizationMembersRoute
  '/$slug/organization/teams': typeof SlugDashboardOrganizationTeamsRoute
  '/$slug/tags/$tagId': typeof SlugDashboardTagsTagIdRoute
  '/$slug/transactions/$transactionId': typeof SlugDashboardTransactionsTransactionIdRoute
  '/$slug/bank-accounts': typeof SlugDashboardBankAccountsIndexRoute
  '/$slug/bills': typeof SlugDashboardBillsIndexRoute
  '/$slug/budgets': typeof SlugDashboardBudgetsIndexRoute
  '/$slug/categories': typeof SlugDashboardCategoriesIndexRoute
  '/$slug/cost-centers': typeof SlugDashboardCostCentersIndexRoute
  '/$slug/organization': typeof SlugDashboardOrganizationIndexRoute
  '/$slug/tags': typeof SlugDashboardTagsIndexRoute
  '/$slug/transactions': typeof SlugDashboardTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$slug': typeof SlugRouteWithChildren
  '/_dashboard': typeof DashboardRoute
  '/auth': typeof AuthRouteWithChildren
  '/$slug/_dashboard': typeof SlugDashboardRouteWithChildren
  '/$slug/onboarding': typeof SlugOnboardingRoute
  '/auth/email-verification': typeof AuthEmailVerificationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/$slug/_dashboard/home': typeof SlugDashboardHomeRoute
  '/$slug/_dashboard/profile': typeof SlugDashboardProfileRoute
  '/$slug/_dashboard/reports': typeof SlugDashboardReportsRoute
  '/$slug/_dashboard/bank-accounts/$bankAccountId': typeof SlugDashboardBankAccountsBankAccountIdRoute
  '/$slug/_dashboard/budgets/$budgetId': typeof SlugDashboardBudgetsBudgetIdRoute
  '/$slug/_dashboard/categories/$categoryId': typeof SlugDashboardCategoriesCategoryIdRoute
  '/$slug/_dashboard/cost-centers/$costCenterId': typeof SlugDashboardCostCentersCostCenterIdRoute
  '/$slug/_dashboard/organization/invites': typeof SlugDashboardOrganizationInvitesRoute
  '/$slug/_dashboard/organization/members': typeof SlugDashboardOrganizationMembersRoute
  '/$slug/_dashboard/organization/teams': typeof SlugDashboardOrganizationTeamsRoute
  '/$slug/_dashboard/tags/$tagId': typeof SlugDashboardTagsTagIdRoute
  '/$slug/_dashboard/transactions/$transactionId': typeof SlugDashboardTransactionsTransactionIdRoute
  '/$slug/_dashboard/bank-accounts/': typeof SlugDashboardBankAccountsIndexRoute
  '/$slug/_dashboard/bills/': typeof SlugDashboardBillsIndexRoute
  '/$slug/_dashboard/budgets/': typeof SlugDashboardBudgetsIndexRoute
  '/$slug/_dashboard/categories/': typeof SlugDashboardCategoriesIndexRoute
  '/$slug/_dashboard/cost-centers/': typeof SlugDashboardCostCentersIndexRoute
  '/$slug/_dashboard/organization/': typeof SlugDashboardOrganizationIndexRoute
  '/$slug/_dashboard/tags/': typeof SlugDashboardTagsIndexRoute
  '/$slug/_dashboard/transactions/': typeof SlugDashboardTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$slug'
    | '/auth'
    | '/$slug/onboarding'
    | '/auth/email-verification'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/$slug/home'
    | '/$slug/profile'
    | '/$slug/reports'
    | '/$slug/bank-accounts/$bankAccountId'
    | '/$slug/budgets/$budgetId'
    | '/$slug/categories/$categoryId'
    | '/$slug/cost-centers/$costCenterId'
    | '/$slug/organization/invites'
    | '/$slug/organization/members'
    | '/$slug/organization/teams'
    | '/$slug/tags/$tagId'
    | '/$slug/transactions/$transactionId'
    | '/$slug/bank-accounts'
    | '/$slug/bills'
    | '/$slug/budgets'
    | '/$slug/categories'
    | '/$slug/cost-centers'
    | '/$slug/organization'
    | '/$slug/tags'
    | '/$slug/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$slug'
    | '/auth'
    | '/$slug/onboarding'
    | '/auth/email-verification'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/$slug/home'
    | '/$slug/profile'
    | '/$slug/reports'
    | '/$slug/bank-accounts/$bankAccountId'
    | '/$slug/budgets/$budgetId'
    | '/$slug/categories/$categoryId'
    | '/$slug/cost-centers/$costCenterId'
    | '/$slug/organization/invites'
    | '/$slug/organization/members'
    | '/$slug/organization/teams'
    | '/$slug/tags/$tagId'
    | '/$slug/transactions/$transactionId'
    | '/$slug/bank-accounts'
    | '/$slug/bills'
    | '/$slug/budgets'
    | '/$slug/categories'
    | '/$slug/cost-centers'
    | '/$slug/organization'
    | '/$slug/tags'
    | '/$slug/transactions'
  id:
    | '__root__'
    | '/$slug'
    | '/_dashboard'
    | '/auth'
    | '/$slug/_dashboard'
    | '/$slug/onboarding'
    | '/auth/email-verification'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/$slug/_dashboard/home'
    | '/$slug/_dashboard/profile'
    | '/$slug/_dashboard/reports'
    | '/$slug/_dashboard/bank-accounts/$bankAccountId'
    | '/$slug/_dashboard/budgets/$budgetId'
    | '/$slug/_dashboard/categories/$categoryId'
    | '/$slug/_dashboard/cost-centers/$costCenterId'
    | '/$slug/_dashboard/organization/invites'
    | '/$slug/_dashboard/organization/members'
    | '/$slug/_dashboard/organization/teams'
    | '/$slug/_dashboard/tags/$tagId'
    | '/$slug/_dashboard/transactions/$transactionId'
    | '/$slug/_dashboard/bank-accounts/'
    | '/$slug/_dashboard/bills/'
    | '/$slug/_dashboard/budgets/'
    | '/$slug/_dashboard/categories/'
    | '/$slug/_dashboard/cost-centers/'
    | '/$slug/_dashboard/organization/'
    | '/$slug/_dashboard/tags/'
    | '/$slug/_dashboard/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SlugRoute: typeof SlugRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/email-verification': {
      id: '/auth/email-verification'
      path: '/email-verification'
      fullPath: '/auth/email-verification'
      preLoaderRoute: typeof AuthEmailVerificationRouteImport
      parentRoute: typeof AuthRoute
    }
    '/$slug/onboarding': {
      id: '/$slug/onboarding'
      path: '/onboarding'
      fullPath: '/$slug/onboarding'
      preLoaderRoute: typeof SlugOnboardingRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/_dashboard': {
      id: '/$slug/_dashboard'
      path: ''
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugDashboardRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/_dashboard/reports': {
      id: '/$slug/_dashboard/reports'
      path: '/reports'
      fullPath: '/$slug/reports'
      preLoaderRoute: typeof SlugDashboardReportsRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/profile': {
      id: '/$slug/_dashboard/profile'
      path: '/profile'
      fullPath: '/$slug/profile'
      preLoaderRoute: typeof SlugDashboardProfileRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/home': {
      id: '/$slug/_dashboard/home'
      path: '/home'
      fullPath: '/$slug/home'
      preLoaderRoute: typeof SlugDashboardHomeRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/transactions/': {
      id: '/$slug/_dashboard/transactions/'
      path: '/transactions'
      fullPath: '/$slug/transactions'
      preLoaderRoute: typeof SlugDashboardTransactionsIndexRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/tags/': {
      id: '/$slug/_dashboard/tags/'
      path: '/tags'
      fullPath: '/$slug/tags'
      preLoaderRoute: typeof SlugDashboardTagsIndexRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/organization/': {
      id: '/$slug/_dashboard/organization/'
      path: '/organization'
      fullPath: '/$slug/organization'
      preLoaderRoute: typeof SlugDashboardOrganizationIndexRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/cost-centers/': {
      id: '/$slug/_dashboard/cost-centers/'
      path: '/cost-centers'
      fullPath: '/$slug/cost-centers'
      preLoaderRoute: typeof SlugDashboardCostCentersIndexRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/categories/': {
      id: '/$slug/_dashboard/categories/'
      path: '/categories'
      fullPath: '/$slug/categories'
      preLoaderRoute: typeof SlugDashboardCategoriesIndexRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/budgets/': {
      id: '/$slug/_dashboard/budgets/'
      path: '/budgets'
      fullPath: '/$slug/budgets'
      preLoaderRoute: typeof SlugDashboardBudgetsIndexRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/bills/': {
      id: '/$slug/_dashboard/bills/'
      path: '/bills'
      fullPath: '/$slug/bills'
      preLoaderRoute: typeof SlugDashboardBillsIndexRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/bank-accounts/': {
      id: '/$slug/_dashboard/bank-accounts/'
      path: '/bank-accounts'
      fullPath: '/$slug/bank-accounts'
      preLoaderRoute: typeof SlugDashboardBankAccountsIndexRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/transactions/$transactionId': {
      id: '/$slug/_dashboard/transactions/$transactionId'
      path: '/transactions/$transactionId'
      fullPath: '/$slug/transactions/$transactionId'
      preLoaderRoute: typeof SlugDashboardTransactionsTransactionIdRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/tags/$tagId': {
      id: '/$slug/_dashboard/tags/$tagId'
      path: '/tags/$tagId'
      fullPath: '/$slug/tags/$tagId'
      preLoaderRoute: typeof SlugDashboardTagsTagIdRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/organization/teams': {
      id: '/$slug/_dashboard/organization/teams'
      path: '/organization/teams'
      fullPath: '/$slug/organization/teams'
      preLoaderRoute: typeof SlugDashboardOrganizationTeamsRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/organization/members': {
      id: '/$slug/_dashboard/organization/members'
      path: '/organization/members'
      fullPath: '/$slug/organization/members'
      preLoaderRoute: typeof SlugDashboardOrganizationMembersRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/organization/invites': {
      id: '/$slug/_dashboard/organization/invites'
      path: '/organization/invites'
      fullPath: '/$slug/organization/invites'
      preLoaderRoute: typeof SlugDashboardOrganizationInvitesRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/cost-centers/$costCenterId': {
      id: '/$slug/_dashboard/cost-centers/$costCenterId'
      path: '/cost-centers/$costCenterId'
      fullPath: '/$slug/cost-centers/$costCenterId'
      preLoaderRoute: typeof SlugDashboardCostCentersCostCenterIdRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/categories/$categoryId': {
      id: '/$slug/_dashboard/categories/$categoryId'
      path: '/categories/$categoryId'
      fullPath: '/$slug/categories/$categoryId'
      preLoaderRoute: typeof SlugDashboardCategoriesCategoryIdRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/budgets/$budgetId': {
      id: '/$slug/_dashboard/budgets/$budgetId'
      path: '/budgets/$budgetId'
      fullPath: '/$slug/budgets/$budgetId'
      preLoaderRoute: typeof SlugDashboardBudgetsBudgetIdRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/bank-accounts/$bankAccountId': {
      id: '/$slug/_dashboard/bank-accounts/$bankAccountId'
      path: '/bank-accounts/$bankAccountId'
      fullPath: '/$slug/bank-accounts/$bankAccountId'
      preLoaderRoute: typeof SlugDashboardBankAccountsBankAccountIdRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
  }
}

interface SlugDashboardRouteChildren {
  SlugDashboardHomeRoute: typeof SlugDashboardHomeRoute
  SlugDashboardProfileRoute: typeof SlugDashboardProfileRoute
  SlugDashboardReportsRoute: typeof SlugDashboardReportsRoute
  SlugDashboardBankAccountsBankAccountIdRoute: typeof SlugDashboardBankAccountsBankAccountIdRoute
  SlugDashboardBudgetsBudgetIdRoute: typeof SlugDashboardBudgetsBudgetIdRoute
  SlugDashboardCategoriesCategoryIdRoute: typeof SlugDashboardCategoriesCategoryIdRoute
  SlugDashboardCostCentersCostCenterIdRoute: typeof SlugDashboardCostCentersCostCenterIdRoute
  SlugDashboardOrganizationInvitesRoute: typeof SlugDashboardOrganizationInvitesRoute
  SlugDashboardOrganizationMembersRoute: typeof SlugDashboardOrganizationMembersRoute
  SlugDashboardOrganizationTeamsRoute: typeof SlugDashboardOrganizationTeamsRoute
  SlugDashboardTagsTagIdRoute: typeof SlugDashboardTagsTagIdRoute
  SlugDashboardTransactionsTransactionIdRoute: typeof SlugDashboardTransactionsTransactionIdRoute
  SlugDashboardBankAccountsIndexRoute: typeof SlugDashboardBankAccountsIndexRoute
  SlugDashboardBillsIndexRoute: typeof SlugDashboardBillsIndexRoute
  SlugDashboardBudgetsIndexRoute: typeof SlugDashboardBudgetsIndexRoute
  SlugDashboardCategoriesIndexRoute: typeof SlugDashboardCategoriesIndexRoute
  SlugDashboardCostCentersIndexRoute: typeof SlugDashboardCostCentersIndexRoute
  SlugDashboardOrganizationIndexRoute: typeof SlugDashboardOrganizationIndexRoute
  SlugDashboardTagsIndexRoute: typeof SlugDashboardTagsIndexRoute
  SlugDashboardTransactionsIndexRoute: typeof SlugDashboardTransactionsIndexRoute
}

const SlugDashboardRouteChildren: SlugDashboardRouteChildren = {
  SlugDashboardHomeRoute: SlugDashboardHomeRoute,
  SlugDashboardProfileRoute: SlugDashboardProfileRoute,
  SlugDashboardReportsRoute: SlugDashboardReportsRoute,
  SlugDashboardBankAccountsBankAccountIdRoute:
    SlugDashboardBankAccountsBankAccountIdRoute,
  SlugDashboardBudgetsBudgetIdRoute: SlugDashboardBudgetsBudgetIdRoute,
  SlugDashboardCategoriesCategoryIdRoute:
    SlugDashboardCategoriesCategoryIdRoute,
  SlugDashboardCostCentersCostCenterIdRoute:
    SlugDashboardCostCentersCostCenterIdRoute,
  SlugDashboardOrganizationInvitesRoute: SlugDashboardOrganizationInvitesRoute,
  SlugDashboardOrganizationMembersRoute: SlugDashboardOrganizationMembersRoute,
  SlugDashboardOrganizationTeamsRoute: SlugDashboardOrganizationTeamsRoute,
  SlugDashboardTagsTagIdRoute: SlugDashboardTagsTagIdRoute,
  SlugDashboardTransactionsTransactionIdRoute:
    SlugDashboardTransactionsTransactionIdRoute,
  SlugDashboardBankAccountsIndexRoute: SlugDashboardBankAccountsIndexRoute,
  SlugDashboardBillsIndexRoute: SlugDashboardBillsIndexRoute,
  SlugDashboardBudgetsIndexRoute: SlugDashboardBudgetsIndexRoute,
  SlugDashboardCategoriesIndexRoute: SlugDashboardCategoriesIndexRoute,
  SlugDashboardCostCentersIndexRoute: SlugDashboardCostCentersIndexRoute,
  SlugDashboardOrganizationIndexRoute: SlugDashboardOrganizationIndexRoute,
  SlugDashboardTagsIndexRoute: SlugDashboardTagsIndexRoute,
  SlugDashboardTransactionsIndexRoute: SlugDashboardTransactionsIndexRoute,
}

const SlugDashboardRouteWithChildren = SlugDashboardRoute._addFileChildren(
  SlugDashboardRouteChildren,
)

interface SlugRouteChildren {
  SlugDashboardRoute: typeof SlugDashboardRouteWithChildren
  SlugOnboardingRoute: typeof SlugOnboardingRoute
}

const SlugRouteChildren: SlugRouteChildren = {
  SlugDashboardRoute: SlugDashboardRouteWithChildren,
  SlugOnboardingRoute: SlugOnboardingRoute,
}

const SlugRouteWithChildren = SlugRoute._addFileChildren(SlugRouteChildren)

interface AuthRouteChildren {
  AuthEmailVerificationRoute: typeof AuthEmailVerificationRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthEmailVerificationRoute: AuthEmailVerificationRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SlugRoute: SlugRouteWithChildren,
  DashboardRoute: DashboardRoute,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
