import type { Currency } from "./types";

/**
 * ISO 4217 currency definitions
 *
 * Includes:
 * - Major world currencies (USD, EUR, GBP, etc.)
 * - Zero decimal currencies (JPY, KRW, VND)
 * - Three decimal currencies (KWD, BHD, OMR)
 * - Popular cryptocurrencies (BTC, ETH)
 */
export const ISO_4217_CURRENCIES: Record<string, Currency> = {
   // Americas
   USD: {
      code: "USD",
      numericCode: 840,
      name: "US Dollar",
      decimalPlaces: 2,
      symbol: "$",
      subunitName: "cent",
   },
   CAD: {
      code: "CAD",
      numericCode: 124,
      name: "Canadian Dollar",
      decimalPlaces: 2,
      symbol: "C$",
      subunitName: "cent",
   },
   MXN: {
      code: "MXN",
      numericCode: 484,
      name: "Mexican Peso",
      decimalPlaces: 2,
      symbol: "$",
      subunitName: "centavo",
   },
   BRL: {
      code: "BRL",
      numericCode: 986,
      name: "Brazilian Real",
      decimalPlaces: 2,
      symbol: "R$",
      subunitName: "centavo",
   },
   ARS: {
      code: "ARS",
      numericCode: 32,
      name: "Argentine Peso",
      decimalPlaces: 2,
      symbol: "$",
      subunitName: "centavo",
   },
   CLP: {
      code: "CLP",
      numericCode: 152,
      name: "Chilean Peso",
      decimalPlaces: 0,
      symbol: "$",
   },
   COP: {
      code: "COP",
      numericCode: 170,
      name: "Colombian Peso",
      decimalPlaces: 2,
      symbol: "$",
      subunitName: "centavo",
   },
   PEN: {
      code: "PEN",
      numericCode: 604,
      name: "Peruvian Sol",
      decimalPlaces: 2,
      symbol: "S/",
      subunitName: "céntimo",
   },

   // Europe
   EUR: {
      code: "EUR",
      numericCode: 978,
      name: "Euro",
      decimalPlaces: 2,
      symbol: "€",
      subunitName: "cent",
   },
   GBP: {
      code: "GBP",
      numericCode: 826,
      name: "Pound Sterling",
      decimalPlaces: 2,
      symbol: "£",
      subunitName: "penny",
   },
   CHF: {
      code: "CHF",
      numericCode: 756,
      name: "Swiss Franc",
      decimalPlaces: 2,
      symbol: "CHF",
      subunitName: "rappen",
   },
   SEK: {
      code: "SEK",
      numericCode: 752,
      name: "Swedish Krona",
      decimalPlaces: 2,
      symbol: "kr",
      subunitName: "öre",
   },
   NOK: {
      code: "NOK",
      numericCode: 578,
      name: "Norwegian Krone",
      decimalPlaces: 2,
      symbol: "kr",
      subunitName: "øre",
   },
   DKK: {
      code: "DKK",
      numericCode: 208,
      name: "Danish Krone",
      decimalPlaces: 2,
      symbol: "kr",
      subunitName: "øre",
   },
   PLN: {
      code: "PLN",
      numericCode: 985,
      name: "Polish Zloty",
      decimalPlaces: 2,
      symbol: "zł",
      subunitName: "grosz",
   },
   CZK: {
      code: "CZK",
      numericCode: 203,
      name: "Czech Koruna",
      decimalPlaces: 2,
      symbol: "Kč",
      subunitName: "haléř",
   },
   HUF: {
      code: "HUF",
      numericCode: 348,
      name: "Hungarian Forint",
      decimalPlaces: 2,
      symbol: "Ft",
      subunitName: "fillér",
   },
   RON: {
      code: "RON",
      numericCode: 946,
      name: "Romanian Leu",
      decimalPlaces: 2,
      symbol: "lei",
      subunitName: "ban",
   },
   RUB: {
      code: "RUB",
      numericCode: 643,
      name: "Russian Ruble",
      decimalPlaces: 2,
      symbol: "₽",
      subunitName: "kopek",
   },
   TRY: {
      code: "TRY",
      numericCode: 949,
      name: "Turkish Lira",
      decimalPlaces: 2,
      symbol: "₺",
      subunitName: "kuruş",
   },
   ISK: {
      code: "ISK",
      numericCode: 352,
      name: "Icelandic Krona",
      decimalPlaces: 0,
      symbol: "kr",
   },

   // Asia & Pacific
   JPY: {
      code: "JPY",
      numericCode: 392,
      name: "Japanese Yen",
      decimalPlaces: 0,
      symbol: "¥",
   },
   CNY: {
      code: "CNY",
      numericCode: 156,
      name: "Chinese Yuan",
      decimalPlaces: 2,
      symbol: "¥",
      subunitName: "fen",
   },
   HKD: {
      code: "HKD",
      numericCode: 344,
      name: "Hong Kong Dollar",
      decimalPlaces: 2,
      symbol: "HK$",
      subunitName: "cent",
   },
   TWD: {
      code: "TWD",
      numericCode: 901,
      name: "New Taiwan Dollar",
      decimalPlaces: 2,
      symbol: "NT$",
      subunitName: "cent",
   },
   KRW: {
      code: "KRW",
      numericCode: 410,
      name: "South Korean Won",
      decimalPlaces: 0,
      symbol: "₩",
   },
   INR: {
      code: "INR",
      numericCode: 356,
      name: "Indian Rupee",
      decimalPlaces: 2,
      symbol: "₹",
      subunitName: "paisa",
   },
   IDR: {
      code: "IDR",
      numericCode: 360,
      name: "Indonesian Rupiah",
      decimalPlaces: 2,
      symbol: "Rp",
      subunitName: "sen",
   },
   MYR: {
      code: "MYR",
      numericCode: 458,
      name: "Malaysian Ringgit",
      decimalPlaces: 2,
      symbol: "RM",
      subunitName: "sen",
   },
   SGD: {
      code: "SGD",
      numericCode: 702,
      name: "Singapore Dollar",
      decimalPlaces: 2,
      symbol: "S$",
      subunitName: "cent",
   },
   THB: {
      code: "THB",
      numericCode: 764,
      name: "Thai Baht",
      decimalPlaces: 2,
      symbol: "฿",
      subunitName: "satang",
   },
   PHP: {
      code: "PHP",
      numericCode: 608,
      name: "Philippine Peso",
      decimalPlaces: 2,
      symbol: "₱",
      subunitName: "sentimo",
   },
   VND: {
      code: "VND",
      numericCode: 704,
      name: "Vietnamese Dong",
      decimalPlaces: 0,
      symbol: "₫",
   },
   AUD: {
      code: "AUD",
      numericCode: 36,
      name: "Australian Dollar",
      decimalPlaces: 2,
      symbol: "A$",
      subunitName: "cent",
   },
   NZD: {
      code: "NZD",
      numericCode: 554,
      name: "New Zealand Dollar",
      decimalPlaces: 2,
      symbol: "NZ$",
      subunitName: "cent",
   },

   // Middle East
   AED: {
      code: "AED",
      numericCode: 784,
      name: "UAE Dirham",
      decimalPlaces: 2,
      symbol: "د.إ",
      subunitName: "fils",
   },
   SAR: {
      code: "SAR",
      numericCode: 682,
      name: "Saudi Riyal",
      decimalPlaces: 2,
      symbol: "﷼",
      subunitName: "halala",
   },
   ILS: {
      code: "ILS",
      numericCode: 376,
      name: "Israeli New Shekel",
      decimalPlaces: 2,
      symbol: "₪",
      subunitName: "agora",
   },

   // Three decimal currencies
   KWD: {
      code: "KWD",
      numericCode: 414,
      name: "Kuwaiti Dinar",
      decimalPlaces: 3,
      symbol: "د.ك",
      subunitName: "fils",
   },
   BHD: {
      code: "BHD",
      numericCode: 48,
      name: "Bahraini Dinar",
      decimalPlaces: 3,
      symbol: ".د.ب",
      subunitName: "fils",
   },
   OMR: {
      code: "OMR",
      numericCode: 512,
      name: "Omani Rial",
      decimalPlaces: 3,
      symbol: "ر.ع.",
      subunitName: "baisa",
   },

   // Africa
   ZAR: {
      code: "ZAR",
      numericCode: 710,
      name: "South African Rand",
      decimalPlaces: 2,
      symbol: "R",
      subunitName: "cent",
   },
   EGP: {
      code: "EGP",
      numericCode: 818,
      name: "Egyptian Pound",
      decimalPlaces: 2,
      symbol: "E£",
      subunitName: "piastre",
   },
   NGN: {
      code: "NGN",
      numericCode: 566,
      name: "Nigerian Naira",
      decimalPlaces: 2,
      symbol: "₦",
      subunitName: "kobo",
   },

   // Cryptocurrencies (non-ISO, using 0 as numeric code)
   BTC: {
      code: "BTC",
      numericCode: 0,
      name: "Bitcoin",
      decimalPlaces: 8,
      symbol: "₿",
      subunitName: "satoshi",
   },
   ETH: {
      code: "ETH",
      numericCode: 0,
      name: "Ethereum",
      decimalPlaces: 18,
      symbol: "Ξ",
      subunitName: "wei",
   },
};
